const types = {
    FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS',
    FACEBOOK_LOGIN_FAIL: 'FACEBOOK_LOGIN_FAIL',
    FACEBOOK_LOGIN_ATTEMPTED: 'FACEBOOK_LOGIN_ATTEMPTED',
    MAP_LOADED: 'MAP_LOADED',
    MAP_REGION_UPDATE: 'MAP_REGION_UPDATE',
    JOBS_FETCH: 'JOBS_FETCH',
    JOB_LIKE: 'JOB_LIKE',
    JOB_LIKED_CLEAR: 'JOB_LIKED_CLEAR'
}

export default types