const types = {
    FACEBOOK_LOGIN_SUCCESS: 'FACEBOOK_LOGIN_SUCCESS',
    FACEBOOK_LOGIN_FAIL: 'FACEBOOK_LOGIN_FAIL',
    FACEBOOK_LOGIN_ATTEMPTED: 'FACEBOOK_LOGIN_ATTEMPTED',
    MAP_LOADED: 'MAP_LOADED',
    MAP_REGION_UPDATE: 'MAP_REGION_UPDATE',
    JOBS_FETCH: 'JOBS_FETCH'
}

export default types